site_name : Documentation afin de calculer le point moyen d’un nuage de points
docs_dir : docs
theme : readthedocs
nav:
  - Home : 'index.md'
  - About : 'about.md'
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search